


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Hume
 */
public class Juga2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Juga2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Versus");

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseClicked(evt);
            }
        });

        filler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler2.setOpaque(true);
        filler2.setBounds(350, 0, 50, 400);
        jLayeredPane1.add(filler2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler4.setOpaque(true);
        filler4.setBounds(0, 0, 50, 400);
        jLayeredPane1.add(filler4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler5.setOpaque(true);
        filler5.setBounds(50, 0, 50, 400);
        jLayeredPane1.add(filler5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler6.setOpaque(true);
        filler6.setBounds(100, 0, 50, 400);
        jLayeredPane1.add(filler6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler7.setOpaque(true);
        filler7.setBounds(150, 0, 50, 400);
        jLayeredPane1.add(filler7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler8.setOpaque(true);
        filler8.setBounds(200, 0, 50, 400);
        jLayeredPane1.add(filler8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler9.setOpaque(true);
        filler9.setBounds(250, 0, 50, 400);
        jLayeredPane1.add(filler9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        filler10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        filler10.setOpaque(true);
        filler10.setBounds(300, 0, 50, 400);
        jLayeredPane1.add(filler10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jTextField2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    int c1, c2;
    static Tauler t;
    static double Ymax;
    static double  Xmax;
    static int  Step;
    static boolean Torn = true;
    static boolean Acabat = false;
    static Jugador player1, player2;
    static Profe player3;
    
    private static int whichx(int col){
        return (Step*col+70);
    }
    
    private static int whichy(int fil){
        return (446-fil*50);
    }

    private void jLayeredPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseClicked
//        // TODO add your handling code here:

        int X = evt.getX();
        int Y = evt.getY();
        int colu;
        int color;
        
        Dimension mides = jLayeredPane1.getSize();
        Ymax = mides.getHeight();
        Xmax = mides.getWidth();
        Step = (int) Xmax/8;
        int col = (int) X/Step;
      //  jTextField1.setText(String.valueOf(col));
        jTextField1.setText(player1.nom());
        jTextField3.setText(player2.nom());
        
        if (!Acabat){
            if (Torn) {
                if ("Manual".equals(player1.nom())){
                    colu = col;
                }
                else{
                    colu = player1.moviment(t,1);
                }
                t.afegeix(colu, 1);
                color=1;
                Torn = !(Torn);        
                jTextField2.setText("TOCA JUGAR "+player2.nom());  
 //               jTextField3.setText(player2.nom()+": "+Float.toString(player3.heuristica(t, -1))); 
//                float pl=player3.heuristica(t, -1); 
            }
            else {
                if ("Manual".equals(player2.nom())){
                    colu = col;
                }
                else{
                    colu = player2.moviment(t,-1);
                }
                t.afegeix(colu, -1);
                color =-1;
                Torn = !(Torn);
                jTextField2.setText("TOCA JUGAR "+player1.nom());                
//                jTextField1.setText(player1.nom()+": "+Float.toString(player3.heuristica(t, 1))); 
//                float pl=player3.heuristica(t, 1);             
            }
            if (t.solucio(colu, color)){
                System.out.println("GUANYAT");   
                if (color==1){jTextField1.setText("GUANYA "+player1.nom());jTextField2.setText("VERMELL AMB MOVIMENT A COLUMNA "+(colu+1));   }
                else {jTextField3.setText("GUANYA "+player2.nom());jTextField2.setText("BLAU AMB MOVIMENT A COLUMNA "+(colu+1));   }         
                Acabat = true;
            }
            else if(!t.espotmoure()){
                System.out.println("NO ES POT MOURE MÉS");
                jTextField1.setText("NO ES POT MOURE MÉS");
                jTextField2.setText("TAULES"); 
                Acabat = true;
            }
        }
        repaint();
    } //GEN-LAST:event_jLayeredPane1MouseClicked

        
    @Override
    public void paint(Graphics g)
    {
     super.paint(g);
     for (int i=0; i<8; i++){
        for (int j=0; j<8; j++){
            if (t.getColor(j, i)==1){ 
                g.setColor(Color.RED);
                g.drawOval(whichx(i),whichy(j),40,40);
                g.fillOval(whichx(i),whichy(j),40,40);
            }
            else if (t.getColor(j, i)==-1) { 
                g.setColor(Color.BLUE);
                g.drawOval(whichx(i),whichy(j),40,40);
                g.fillOval(whichx(i),whichy(j),40,40);
            }
        }
     }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Juga2().setVisible(true);
            }
        });
        t = new Tauler(8);

        //player1 = new Profe(6,true);
        //player2 = new Aleatori();
        player1 = new Ferran();
        player2 = new Profe(6,false);
        //player1 = new Manual();
        //player2= new Manual();
    }
    

    // Variables declaration - do not modify
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration
}
