//Escribe la barra lateral en el estilo styleblue.css
var sbar='<ul><li><div class="post2">Secciones</div><ul><li><a href="http://norfipc.com/index.html">Inicio</a></li><li><a href="http://norfipc.com/facebook/index.html">Para Facebook</a></li><li><a href="http://norfipc.com/amor/index.php">Amor</a></li><li><a href="http://norfipc.com/celulares/index.html">Celulares y tabletas</a></li><li><a href="http://norfipc.com/internet/index.html">Navegar en internet</a></li><li><a href="http://norfipc.com/redes-sociales/index.html">Redes sociales</a></li><li><a href="http://norfipc.com/articulos/index.html">Como lo hago</a></li><li><a href="http://norfipc.com/trucos/index.php">Trucos e Ideas</a></li><li><a href="http://norfipc.com/utiles/index.html">Modificar Windows</a></li><li><a href="http://norfipc.com/comandos/index.html">Comandos</a></li><li><a href="http://norfipc.com/registro/index.html">El Registro</a></li><li><a href="http://norfipc.com/virus/index.html">Virus</a></li><li><a href="http://norfipc.com/redes/index.html">Redes</a></li><li><a href="http://norfipc.com/descargas-gratis/index.html">Descargas gratis</a></li><li><a href="http://norfipc.com/web/index.html">Diseño web</a></li><li><a href="http://norfipc.com/web/publicar-blog-sitio-web-servicios-internet.php">Publicación web</a></li><li><a href="http://norfipc.com/web/optimizar-mejorar-posicionamiento-web-buscadores.php">Posicionamiento web</a></li><li><a href="http://norfipc.com/herramientas/index.php">Herramientas web</a></li><li><a href="http://norfipc.com/codigos/index.php">Códigos</a></li><li><a href="http://norfipc.com/inf/index.html">Informaciones</a></li><li><a href="http://norfipc.com/infografia/index.html">Infografías</a></li><li><a href="http://norfipc.com/recuperar/index.html">Recuperar</a></li><li><a href="http://norfipc.com/mensajes-cristianos/index.php">Mensajes cristianos</a></li><li><a href="https://norfipc.com/fotos-naturaleza/index.php">Fotos de la naturaleza</a></li><li><a href="http://norfipc.com/cuba/index.html">Cuba</a></li><li><a href="http://norfipc.com/about/index.php">Como lo hacemos</a></li></ul></li></ul><div class="post2">Blogs</div><ul><li><ul><li><a rel="nofollow" href="http://norfipc.blogspot.com/">Blog de Norfi Carrodeguas en Blogger</a></li></ul></li></ul><br><div class="fb-like-box" data-href="http://www.facebook.com/norfipc.trucos" data-width="240" data-show-faces="true" data-stream="false" data-header="true"></div><br><br><div id="qrcode"></div>';
document.getElementById('sidebar').innerHTML=sbar;

//Escribe Codigo QR
var dir=window.document.URL;
document.getElementById('qrcode').innerHTML='<img src="https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl='+dir+'" width="150" height="150">';



